[package]
name = 'ffxiv-sqliteway'
version = '0.1.0'
edition = '2021'
description = 'lol'

[dependencies]
csv = '1.1.6'
anyhow = '1.0.57'

[dependencies.clap]
default-features = false
features = ['std', 'derive']
version = '3.1.18'

[[bin]]
name = 'ffxiv-sqliteway'
path = 'ffxiv-sqliteway.rs'
