# vim: sw=1
on:
 push:
  branches:
  - develop

env:
 CARGO_TERM_COLOR: always

jobs:
 ffxiv-sqliteway:
  runs-on: ubuntu-22.04
  steps:
  -
   uses: actions/checkout@v3
   with:
    submodules: false
  -
   uses: actions/cache@v3
   with:
    path: |
     ~/.cargo/registry/index/
     ~/.cargo/registry/cache/
     target/
    key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-r1

  - run: cargo build --release

  -
   uses: actions/upload-artifact@v3
   with:
    name: ffxiv-sqliteway
    path: target/release/ffxiv-sqliteway
    if-no-files-found: error

 database:
  strategy:
   matrix:
    distro: [ko, global]
  runs-on: ubuntu-22.04
  needs: ffxiv-sqliteway
  steps:
  -
   uses: actions/checkout@v3
   with:
    submodules: false
  - run: git submodule --init data/${{ matrix.distro }}/
  -
   uses: actions/download-artifact@v3
   with:
    name: ffxiv-sqliteway
  -
   run: >-
    chmod +x ffxiv-sqliteway &&
    ./ffxiv-sqliteway
    --from=data/${{ matrix.distro }}/csv/
    --write-sql=create.sql
    --write-command=csv-cmd
  -
   id: db
   run: >-
    echo "db_filename=${{ matrix.distro }}-$(cd data/${{ matrix.distro }}/
    && git tag).db"
    >> $GITHUB_ENV

  - run: sqlite3 "${{ env.db_filename }}" < create.sql
  - run: sqlite3 "${{ env.db_filename }}" < csv-cmd
  -
   uses: actions/upload-artifact@v3
   with:
    name: "${{ env.db_filename }}"
    path: "${{ env.db_filename }}"
    if-no-files-found: error
